"""empty message

Revision ID: 27dc253223d6
Revises: 6252f3ccd2f0
Create Date: 2026-06-04 18:17:23.407485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '27dc253223d6'
down_revision: Union[str, Sequence[str], None] = '6252f3ccd2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, sever_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.drop_column('crated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
